# Generated by Django 4.0.1 on 2022-01-09 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0003_categoriespc_ordinateur_likes_alter_ordinateur_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corps', models.TextField()),
                ('maj', models.DateTimeField(auto_now=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('ordi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.ordinateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-maj', '-creation'],
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
