# Generated by Django 4.0.1 on 2022-01-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_message_delete_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesPc',
            new_name='Categorie',
        ),
    ]
