# Generated by Django 4.0.1 on 2022-01-12 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0006_ordinateur_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='message_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='ordinateur',
            name='likes',
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='likes',
            field=models.ManyToManyField(related_name='ordi_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
