# Generated by Django 4.0.1 on 2022-01-13 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projet', '0007_message_likes_remove_ordinateur_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinateur',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='ordi_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
