# Generated by Django 4.0.1 on 2022-01-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0010_imagesordi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesordi',
            old_name='photos',
            new_name='photo',
        ),
    ]
